Select distinct JOB_ID from EMPLOYEES;
SELECT avg(SALARY) from EMPLOYEES where JOB_ID='IT_PROG';
SELECT avg(SALARY), JOB_ID from EMPLOYEES group by JOB_ID;
SELECT avg(SALARY), JOB_ID from EMPLOYEES group by JOB_ID having avg(SALARY) >5000;
SELECT SALARY from EMPLOYEES order by SALARY desc ;
select max(SALARY) from EMPLOYEES;
select * from EMPLOYEES where SALARY = (select max(SALARY) from EMPLOYEES);
select max(SALARY) from EMPLOYEES where SALARY<(select max(SALARY) from EMPLOYEES);
select * from EMPLOYEES where SALARY=(select max(SALARY) from EMPLOYEES where SALARY<(select max(SALARY) from EMPLOYEES));
select * from EMPLOYEES where ROWNUM<11 ;
select * from EMPLOYEES order by SALARY desc ;
select * from (select * from EMPLOYEES order by SALARY desc )where ROWNUM<11;
select FIRST_NAME as "given name" from EMPLOYEES;
select LAST_NAME as surname from EMPLOYEES;
select FIRST_NAME||' '||LAST_NAME as full_name from EMPLOYEES;
select EMAIL ||'@gmail.com'as full_email from EMPLOYEES;
select lower(EMAIL ||'@gmail.com')as full_email from EMPLOYEES;
select FIRST_NAME, length(FIRST_NAME) as "name_length" from EMPLOYEES order by "name_length" desc ;
select substr(FIRST_NAME,0,1)||'.'||substr(LAST_NAME,0,1) as initials from EMPLOYEES;
select substr(FIRST_NAME,0,1)||'.'||substr(LAST_NAME,0,1) as initials,FIRST_NAME||' '||LAST_NAME as full_name,lower(EMAIL ||'@gmail.com')as full_email from employees;
CREATE VIEW emailList as select substr(FIRST_NAME,0,1)||'.'||substr(LAST_NAME,0,1) as initials,FIRST_NAME||' '||LAST_NAME as full_name,lower(EMAIL ||'@gmail.com')as full_email from employees;
SELECT * from emailList;
select full_name from emailList;
select min(SALARY)  from (Select * from EMPLOYEES order by SALARY desc ) where ROWNUM<15;
SELECT * from EMPLOYEES where SALARY=(select min(SALARY)  from (Select * from EMPLOYEES order by SALARY desc ) where ROWNUM<15);
SELECT min(SALARY) over from (select distinct SALARY from EMPLOYEES order by SALARY desc ) where ROWNUM<15;
select * from EMPLOYEES where SALARY=(SELECT min(SALARY) over from (select distinct SALARY from EMPLOYEES order by SALARY desc ) where ROWNUM<15);
